### ISSUE TITLE
KeyError: 'gptj' 문제에 대해서

### ISSUE THREAD

**Issue by jin8** [kakaobrain/kogpt#13]
안녕하세요. 예제를 돌려 보려고 했는데 
아래에 에러가 발생해서요.

현재 pytorch==1.10.0, transformers==4.2.2 사용하고 있습니다.
huggingface transformers 패키지 버전이 낮아서 발생하는 문제일까요?

`Traceback (most recent call last):
  File "inference.py", line 8, in <module>
    bos_token='[BOS]', eos_token='[EOS]', unk_token='[UNK]', pad_token='[PAD]', mask_token='[MASK]')
  File "/anaconda3/envs/pytorch/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 352, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/anaconda3/envs/pytorch/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 363, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'gptj'`

**Comment by wbaek** [comment]
https://github.com/kakaobrain/kogpt/blob/main/requirements.txt
transformers는 4.12.0이후 버전을 사용하셔야 합니다.
